# Generated by Django 5.0.4 on 2024-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('amenities', models.TextField()),
                ('description', models.TextField()),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
