# Generated by Django 5.0.4 on 2024-05-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
