# Generated by Django 5.0.4 on 2024-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('commercial', 'Commercial'), ('flat', 'Flat')], max_length=20),
        ),
    ]
