# Generated by Django 5.0.4 on 2024-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_listing_flat_size_listing_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('commercial', 'Commercial Space'), ('flat', 'Flat/Villa')], max_length=20),
        ),
    ]
